### ISSUE TITLE
Ognl.getValue  MemberAccess implementation must be provided!

### ISSUE THREAD

**Issue by xiaoacaia** [yeecode/MyBatisDemo#19]
示例15中，直接使用 Ognl.getValue  会报：MemberAccess implementation must be provided! 的错误
作者是这样解释的：the best way is to implement your own AccessMember which will suite your project best, you can base on existing [DefaultAccessMember](https://github.com/orphan-oss/ognl/blob/master/src/test/java/ognl/DefaultMemberAccess.java) and adjust it to your needs，最好的方式就是：基于你的项目去实现你自己的 AccessMember 

可以使用 mybatis 提供的 OgnlCache 进行验证

**Comment by yeecode** [comment]
我又运行示例15验证了一下，没有发现这个问题。

请确认你在运行时，使用的ognl版本是3.1.24（即示例15的pom中指定的版本）。因为该版本为MemberAccess提供了默认的实现DefaultMemberAccess，该实现是可以完成对象属性的获取的。

该版本能较好地展示ognl的功能，而不需要其他让人分心的配置工作。

---

如果发生你反馈的错误，应该是使用了ognl的更高版本引发。例如，在mybatis的3.5.2中，ognl的版本为3.2.10.。则会出现上述问题。这是因为需要额外为MemberAccess提供实现。

这一实现在mybatis中也是存在的，即mybatis中的[OgnlMemberAccess](https://github.com/yeecode/MyBatisCN/blob/489e130b318d4e46f0b2e70a5ed71b25914bda20/src/main/java/org/apache/ibatis/scripting/xmltags/OgnlMemberAccess.java)类，在org.apache.ibatis.scripting.xmltags路径下。

---

所以，你应该可是直接clone示例15的代码完成Demo；也可以使用mybatis中的ognl完成Demo。如果选择后者的话，不要忘记拷贝其中的OgnlMemberAccess类以便为MemberAccess提供实现。
